default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/stack_overflow_clone_development

test:
  <<: *default
  database: db/stack_overflow_clone_test
